language: php

php:
  - 7.3

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.6"
  global:
    - SHOPWARE_DIRECTORY=${HOME}/shop
    - PLUGIN_DIRECTORY=${SHOPWARE_DIRECTORY}/custom/plugins

cache:
   directories:
     - ${HOME}/.composer/cache/files

install:
  - composer install

before_script:
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
  - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit

    
branches:
  only:
    - feature/travis

script:
  - ./.travis/test.sh
