#!/bin/sh
#
#  _____ _                                        _____ _                    _____                _
# / ____| |                                      / ____| |                  / ____|              | |
#| (___ | |__   ___  _ ____      ____ _ _ __ ___| (___ | |_ __ _  __ _  ___| |     _ __ ___  __ _| |_ ___  _ __
# \___ \| '_ \ / _ \| '_ \ \ /\ / / _` | '__/ _ \\___ \| __/ _` |/ _` |/ _ \ |    | '__/ _ \/ _` | __/ _ \| '__|
# ____) | | | | (_) | |_) \ V  V / (_| | | |  __/____) | || (_| | (_| |  __/ |____| | |  __/ (_| | || (_) | |
#|_____/|_| |_|\___/| .__/ \_/\_/ \__,_|_|  \___|_____/ \__\__,_|\__, |\___|\_____|_|  \___|\__,_|\__\___/|_|
#                  | |                                           __/ |
#                  |_|                                          |___/
#
# Version 2.0
# Author: Stefano Rutishauser
# Description: Creates shop copy of a working Shopware 5.X or Shopware 6.X
# instance into subfolder named "stage".

#set working directory as variable
scriptPath="$( cd "$(dirname "$0")" ; pwd -P )"
shopDir=$scriptPath/..

#check if logfile exists ex. from previous runnings
logFile="$scriptPath/ssc_log.txt"

if  [[ -f "${logFile}" ]]; then
  rm -f ${logFile}
fi

#create logfile
touch ${logFile}

#includes all nessesary functions
source "${scriptPath}/functions.sh"

initialTest

#note starttime
logEntry
